### ISSUE TITLE
selling price suggested action

### ISSUE THREAD

**Issue by pettrs** [cbrewitt/flipping-copilot#1]
when selling an inventory after collecting, you have to do it in the order that the suggest action provides, or else it won't provide a suggested price. so if i have a full inventory of things i just collected i can't just do it freely

**Comment by pettrs** [comment]
a variant of this also happens where it won't suggest you a sell price if  you try to sell item B when it suggests you sell item A first

https://github.com/cbrewitt/flipping-copilot/assets/75093127/e7518899-f691-4a12-9ce0-46af089003e0

**Comment by cbrewitt** [comment]
This would be a nice feature to have. It will require some changes to the back-end.

**Comment by cbrewitt** [comment]
This has now been addressed.
