### ISSUE TITLE
Possible market maniopulation method

### ISSUE THREAD

**Issue by pettrs** [cbrewitt/flipping-copilot#2]
the model appears to be heavily suggesting frequent flipped items in between users, so when new items are introduced to the algorythm, the item spikes. O liquidated a few items yesterday to clear up some money for flipping, as I sold a torva helm, it appeared to be suggested as a buy item for other users and the item quickly spiked in price. i can't say for sure but it kept recommending me to buy and sell the helmet right after i sold it and i think it's safe to assume others were too.

this screenshot shows where i sold a torva helm
![image](https://github.com/cbrewitt/flipping-copilot/assets/75093127/d2c6da4a-65c2-4c4e-aacf-6b6da3203086)

**Comment by cbrewitt** [comment]
Thank you for the concern. However, it is not safe to assume others were getting the same recommendations as you. In fact, the algorithm tries to avoid giving suggestions that lead to users competing for the same items.
