### ISSUE TITLE
Item Profit just completely wrong

### ISSUE THREAD

**Issue by emerald000** [cbrewitt/flipping-copilot#8]
From time to time, I notice a flipping profit different than it actually was. I can't seem to find any pattern/reason for it and it's hard to know exactly how frequently it happens as it might happen on a smaller scale which is much harder to detect. For example:

![RuneLite_Ex6tU1vYzc](https://github.com/user-attachments/assets/23abc85e-7f63-4078-ab70-56afab7c2eb5)
![RuneLite_1KZ4FEHoS1](https://github.com/user-attachments/assets/9628322c-c0b1-4e48-a45e-b08cc9869353)
![RuneLite_9jP6pHpcXA](https://github.com/user-attachments/assets/4f0ebb03-fd1c-4ea1-a198-e0d63bdd0640)

I know it's not much info to go on, but I figured I might as well open an issue.

**Comment by emerald000** [comment]
I found a reproducible situation:

- Have a completed Sell offer in the GE. The sidebar will show "Item: x gp"
- Hop worlds. The sidebar now shows "Item: 2x gp"
- Keep hopping and see the profit growing.

**Comment by cbrewitt** [comment]
Thank you for bringing this to attention, it's very useful to have a way of reproducing this.

**Comment by cbrewitt** [comment]
This has been fixed in v1.5.0
